export default {
    LOAD_USERS_START: 'LOAD_USERS_START',
    LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
    LOAD_USERS_FAIL: 'LOAD_USERS_FAIL',

    LOAD_STATISTICS_START: 'LOAD_STATISTICS_START',
    LOAD_STATISTICS_SUCCESS: 'LOAD_STATISTICS_SUCCESS',
    LOAD_STATISTICS_FAIL: 'LOAD_STATISTICS_FAIL',

    ADD_NOTE_START: 'ADD_NOTE_START',
    ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',
    ADD_NOTE_FAIL: 'ADD_NOTE_FAIL',

    DELETE_NOTE_START: 'DELETE_NOTE_START',
    DELETE_NOTE_SUCCESS: 'DELETE_NOTE_SUCCESS',
    DELETE_NOTE_FAIL: 'DELETE_NOTE_FAIL',
};